[build]
  # Comando para build da aplicação
  command = "pnpm run build"
  # Diretório onde ficam os arquivos buildados
  publish = "dist"

[build.environment]
  # Versão do Node.js
  NODE_VERSION = "18"
  # Usar pnpm como package manager
  NPM_FLAGS = "--version"

# Configurações para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configurações para preview de branches
[context.branch-deploy]
  command = "pnpm run build"

[context.deploy-preview]
  command = "pnpm run build"

# Configurações de desenvolvimento
[context.dev]
  command = "pnpm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"

# Configurações para formulários (se necessário)
[forms]
  # Ativar detecção automática de formulários
  # spam_protection = true

# Configurações de funções serverless (se necessário no futuro)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"