[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"

# Redirect para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers básicos de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"