[build]
  # Comando para build da aplicação
  command = "npm run build"
  # Diretório onde ficam os arquivos buildados
  publish = "dist"
  # Ignorar cache do node_modules para builds mais limpos
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  # Versão do Node.js atualizada
  NODE_VERSION = "22"
  # Usar npm como package manager
  NPM_FLAGS = "--version"
  # Otimizações de build
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"

# Configurações para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança aprimorados
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Content Security Policy para maior segurança
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://bbyzrywmgjiufqtnkslu.supabase.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://bbyzrywmgjiufqtnkslu.supabase.co wss://bbyzrywmgjiufqtnkslu.supabase.co; frame-ancestors 'none';"
    # Permissions Policy
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    # Strict Transport Security
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Cache otimizado para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    # Compressão
    Content-Encoding = "gzip"

# Cache para arquivos específicos
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para imagens
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configurações para preview de branches
[context.branch-deploy]
  command = "npm run build"
  [context.branch-deploy.environment]
    NODE_ENV = "production"

[context.deploy-preview]
  command = "npm run build"
  [context.deploy-preview.environment]
    NODE_ENV = "production"

# Configurações de produção
[context.production]
  command = "npm run build"
  [context.production.environment]
    NODE_ENV = "production"
    GENERATE_SOURCEMAP = "false"

# Configurações para formulários (se necessário)
[forms]
  # Ativar detecção automática de formulários
  # spam_protection = true

# Configurações de funções serverless (se necessário no futuro)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"